Changed "--ext" with "--files"/"-f"
zposten/unorepo pull request #22
Opened 2020-07-29 19:44 UTC by idandagan1

This is regarding to #6

2020-07-31 17:50 UTC, zposten commented
Hi again @idandagan1, thanks for the PR!

2020-07-31 17:59 UTC, zposten commented
This isn't a super big deal in this particular PR because it only has one content commit (so I can squash merge it), but I would appreciate it going forward if you could make sure you start working off of the latest master.  Doing so avoids unnecessary merge commits like the one that exists in this PR (`a2421a4`).

If you run:

```bash
 git log --oneline --decorate --graph --all
```

in this repo, you'll see that there is a perfectly linear history.  I would like to maintain that linear history going forward.  

Like I said, it's not a big deal here because there's only one content commit I'm able to squash merge the PR without any loss of history.

2020-07-31 18:05 UTC, 0livare requested changes

2020-07-31 18:05 UTC, 0livare commented on README.md
> +uno watch --files ts,scss
Did you run this example command after making this change?  It didn't work for me.

2020-07-31 18:05 UTC, 0livare commented on src/unorepo.js
> +  .option('-f, --files <exts>', 'The file extensions to watch', splitList)
The reason it doesn't work is because when you change the name of this flag, you also change the name of the property on the `args` object that gets passed to `commands/watch.js`

2020-07-31 19:46 UTC, idandagan1 commented on src/unorepo.js
> +  .option('-f, --files <exts>', 'The file extensions to watch', splitList)
My bad, I did my tests on a different branch.

Maybe it would be a good idea to add tests to the repo.
Do you want me to add some?

2020-07-31 19:56 UTC, idandagan1 commented
Hi @zposten ,
in regards to the commit `a2421a4`,
I wanted my forked branch to be up-to-date with upstream/master.
So I've ran the commands ([reference](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)):
```
git fetch upstream
git merge upstream/master
```

What's the right way so I can be synced with upstream/master?

2020-07-31 20:09 UTC, idandagan1 commented
And I'll start using [conventional commits](www.conventionalcommits.org)

2020-07-31 20:12 UTC, zposten commented on src/unorepo.js
> +  .option('-f, --files <exts>', 'The file extensions to watch', splitList)
That would be absolutely wonderful! I’ve become a fan of the Jest testing framework lately. Are you familiar with it?

2020-07-31 20:17 UTC, idandagan1 commented on src/unorepo.js
> +  .option('-f, --files <exts>', 'The file extensions to watch', splitList)
Yep :)
Jest is great.

I'll do that.

2020-08-01 13:05 UTC, zposten commented
> Hi @zposten ,
> in regards to the commit `a2421a4`,
> I wanted my forked branch to be up-to-date with upstream/master.
> So I've ran the commands ([reference](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork)):
> 
> ```
> git fetch upstream
> git merge upstream/master
> ```
> 
> What's the right way so I can be synced with upstream/master?

Your simple question has a surprisingly complicated answer.  I'm going to try and explain it thoroughly, but please let me know if something I'm saying is confusing.

For reference, here is the git graph created by your running those two commands:

```git
*   9f36621 Merge remote-tracking branch 'origin/master' [Idan]
|\  
| * 61284d8 Changed "--ext" to "--files" (#6) [Idan]
* | dd27aca fix(watch): Rename flag --ext -> --files [Idan]
|/  
*   a2421a4 Merge remote-tracking branch 'upstream/master' [Idan]
|\  
| * f2a296a (upstream/master) chore: Add lerna as a peer dependency (#21) [Idan Dagan]
* | 7607386 Fixed PR changes [Idan]
* | 63ab869 Added lerna as peer dependency (#18) [Idan]
|/  
* 1055038 doc(watch): Remove text around building dependencies [Zach Posten]
```

The problems all started because I squash merged your previous pull request (#21) to create a single commit out of those two commits which together did one thing.  You can see that by looking at the the fork at the bottom of that graph.  `1055038` splits onto two paths -- one to `63ab869` and one to `f2a296a`.  The former is your original 2 commits and the latter is my squashed commit.

When you ran `git fetch upstream`, git fetched the additional commit that was created by the squash -- `f2a296a` -- from the server.  Even though your branch had exactly the same contents as the squashed branch, they were completely separate commit paths.  So when you then ran `git merge upstream/master` git connected these two paths with a merge commit.

That merge commit is problematic.  By creating it you've added three additional commits to the repository (your original 2 and the merge commit) that don't add any code changes to the repo, because `upstream/master` already had the contents of your merged pull request.  Does that make sense?  I know it's super confusing.

So to answer your question, the correct thing for you to do when you want to start working off of `upstream/master` is

```bash
git fetch --all
git checkout master
git reset --hard upstream/master # Make sure you don't have pending changes when running this
```

Be careful when doing this that you don't have any uncommited changes that you want to keep.  These commands will update your local git with all the remote changes, and then move your `master` branch to the same locat

2020-08-01 13:16 UTC, zposten commented on src/unorepo.js
> +  .option('-f, --files <exts>', 'The file extensions to watch', splitList)
The tests look amazing.  Thank you very much for doing that!

2020-08-03 04:05 UTC, idandagan1 commented
@zposten thanks for the thorough answer.

I don't think it's a good idea to move the tests inside the **src** directory.
it's really common to way to separate tests from src files (almost every open-source project do that).

The test directory usually maintains the same structure of the src folder that way you can navigate easily and see the status of the test.

2020-08-04 22:23 UTC, zposten commented
@idandagan1 After some thought, I agree with you, thanks for bringing that up.  Additionally, keeping them in a separate directory ensures that they won't be pushed to NPM when a new version of the package is published (we could of course manage that in other ways, but it's currently pushing every JS file in the `src` directory, and I like the simplicity of that).

I have updated that `test` branch again, so you should still be able to follow the steps I [suggested](https://github.com/zposten/unorepo/pull/22#issuecomment-667791257) previously to update this PR with those cleaned up commits.

One other thing -- when I was trying to run these tests I noticed that my `yarn install` wouldn't work.  After some investigation I realized it was because the lock file was full of references to `http://repo.lusha.local:8081`, which I found originated in #21.  So watch out for that I guess.

2020-08-05 04:15 UTC, idandagan1 commented
@zposten done.
(sorry for the yarn.lock, I'll be careful next time).

2020-08-05 06:12 UTC, 0livare approved these changes

2020-08-05 06:13 UTC, merged

2022-04-28 09:00 UTC, cmario92 commented
you never released this, right?

2022-04-28 09:34 UTC, idandagan1 commented
I didn’t..

2022-04-28 11:18 UTC, cmario92 commented
all good, just the Readme file mentions the `--file` flag -> use `--ext` instead to specify the file formats

2022-04-28 14:10 UTC, zposten commented
Thanks for pointing that out @cmario92! I dropped the ball on it.  `v0.2.0` has now been released with this change.